import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import type { RowDataPacket } from "mysql2/promise";
import { applyCanonicalMigrations, MAIN_MIGRATIONS_DIR } from "../../../_core/canonical-migrations";
import { getPool } from "../../../db";
import { getTestDatabaseUrl, isTestDatabaseEnabled } from "../../../test-integration-gates";
import { SupplierRepository } from "./repository";
import { SupplierService, type SupplierEventPublisher } from "./service";

const physical=describe.runIf(isTestDatabaseEnabled());
const adminA={clientId:"supplier-a",userId:"admin-a",role:"admin" as const}; const managerA={...adminA,userId:"manager-a",role:"manager" as const}; const agentA={...adminA,userId:"agent-a",role:"agent" as const}; const viewerA={...adminA,userId:"viewer-a",role:"viewer" as const}; const adminB={clientId:"supplier-b",userId:"admin-b",role:"admin" as const};
let serial=0; const input=(changes:Record<string,unknown>={})=>({legalName:`Fornecedor ${++serial}`,tradeName:null,personType:"legal" as const,taxId:`12345678${String(serial).padStart(6,"0")}`,stateRegistration:null,email:`supplier-${serial}@example.com`,phone:null,contactName:null,postalCode:null,street:null,addressNumber:null,addressComplement:null,district:null,city:"Recife",state:"PE",notes:null,...changes});
async function clean(){await getPool().execute("DELETE FROM erp_suppliers WHERE client_id IN (?,?)",[adminA.clientId,adminB.clientId]);}
async function count(sql:string,parameters:unknown[]=[]){const[rows]=await getPool().execute<RowDataPacket[]>(sql,parameters);return Number(rows[0]?.total??0);}
const silent:SupplierEventPublisher={publish:()=>undefined}; const service=()=>new SupplierService(new SupplierRepository(),silent);

physical("ERP suppliers MySQL behavior matrix",()=>{
  beforeAll(async()=>applyCanonicalMigrations(getTestDatabaseUrl(),MAIN_MIGRATIONS_DIR)); beforeEach(clean); afterAll(clean);
  it("01 migration creates the supplier constraints",async()=>{const [rows]=await getPool().execute<RowDataPacket[]>("SHOW INDEX FROM erp_suppliers WHERE Key_name='uq_erp_suppliers_tenant_tax_id'");expect(rows).toHaveLength(2);});
  it("02 creates, normalizes and exposes no internal id",async()=>{const item=await service().create(adminA,input({tradeName:" ",taxId:"12.345.678/0001-90",email:" TEST@EXAMPLE.COM ",postalCode:"01.234-567",state:"pe"}));expect([item.tradeName,item.taxId,item.email,item.postalCode,item.state]).toEqual([null,"12345678000190","test@example.com","01234567","PE"]);expect(item).not.toHaveProperty("id");expect(item).not.toHaveProperty("clientId");});
  it("03 edits every supplier field",async()=>{const s=service();const item=await s.create(adminA,input());const edited=await s.update(adminA,item.publicId,input({legalName:"Editado",tradeName:"Fantasia",personType:"individual",taxId:"123.456.789-01",stateRegistration:"ISENTO",email:"EDITADO@EXAMPLE.COM",phone:"81999990000",contactName:"Contato",postalCode:"50000-000",street:"Rua B",addressNumber:"20",addressComplement:"Sala",district:"Centro",city:"Olinda",state:"pe",notes:"Notas"}));expect(edited).toMatchObject({legalName:"Editado",tradeName:"Fantasia",personType:"individual",taxId:"12345678901",stateRegistration:"ISENTO",email:"editado@example.com",phone:"81999990000",contactName:"Contato",postalCode:"50000000",street:"Rua B",addressNumber:"20",addressComplement:"Sala",district:"Centro",city:"Olinda",state:"PE",notes:"Notas"});});
  it("04 deactivates and activates without deletion",async()=>{const s=service();const item=await s.create(adminA,input());await s.setActive(adminA,item.publicId,false);expect((await s.detail(adminA,item.publicId)).active).toBe(false);await s.setActive(adminA,item.publicId,true);expect((await s.detail(adminA,item.publicId)).active).toBe(true);});
  it("05 rejects duplicate tax id in one tenant",async()=>{const s=service();const command=input();await s.create(adminA,command);await expect(s.create(adminA,{...input(),taxId:command.taxId})).rejects.toMatchObject({code:"CONFLICT"});});
  it("06 permits the same tax id in another tenant",async()=>{const s=service();const command=input();await s.create(adminA,command);expect((await s.create(adminB,{...input(),taxId:command.taxId})).taxId).toBe(command.taxId);});
  it("07 uses uniform not-found errors for cross-tenant detail and mutations",async()=>{const s=service();const item=await s.create(adminA,input());await expect(s.detail(adminB,item.publicId)).rejects.toMatchObject({code:"NOT_FOUND"});await expect(s.update(adminB,item.publicId,input())).rejects.toMatchObject({code:"NOT_FOUND"});await expect(s.setActive(adminB,item.publicId,false)).rejects.toMatchObject({code:"NOT_FOUND"});await expect(s.detail(adminA,crypto.randomUUID())).rejects.toMatchObject({code:"NOT_FOUND"});});
  it.each([adminA,managerA,agentA,viewerA])("08-11 allows $role to read",async identity=>{const s=service();await s.create(adminA,input());expect((await s.list(identity,{search:"",sort:"legalName",direction:"asc",page:1,pageSize:20})).total).toBe(1);});
  it.each([adminA,managerA])("12-13 allows $role to write",async identity=>expect((await service().create(identity,input())).publicId).toBeTruthy());
  it.each([agentA,viewerA])("14-15 rejects $role writes",async identity=>await expect(service().create(identity,input())).rejects.toMatchObject({code:"FORBIDDEN"}));
  it("16 rolls back a failed duplicate",async()=>{const s=service();const command=input();await s.create(adminA,command);await expect(s.create(adminA,{...input(),taxId:command.taxId})).rejects.toBeTruthy();expect(await count("SELECT COUNT(*) total FROM erp_suppliers WHERE client_id=?",[adminA.clientId])).toBe(1);});
  it("17 resolves concurrent duplicates with one physical row",async()=>{const s=service();const command=input();const results=await Promise.allSettled([s.create(adminA,command),s.create(adminA,{...input(),taxId:command.taxId})]);expect(results.filter(result=>result.status==="fulfilled")).toHaveLength(1);expect(await count("SELECT COUNT(*) total FROM erp_suppliers WHERE client_id=? AND tax_id=?",[adminA.clientId,command.taxId])).toBe(1);});
  it("18 searches, filters, orders and paginates server-side",async()=>{const s=service();const zulu=await s.create(adminA,input({legalName:"Zulu Razão",tradeName:"Fantasia Z",taxId:"98.765.432/0001-10",email:"zulu@example.com",city:"Olinda",state:"PE"}));const alfa=await s.create(adminA,input({legalName:"Alfa Razão",tradeName:"Fantasia A",taxId:"12.345.678/0001-90",email:"alfa@example.com",city:"Recife",state:"PE"}));await s.setActive(adminA,zulu.publicId,false);for(const search of ["Alfa Razão","Fantasia A","12.345.678/0001-90","alfa@example.com"]){const found=await s.list(adminA,{search,sort:"legalName",direction:"asc",page:1,pageSize:20});expect(found.items.map(item=>item.publicId)).toEqual([alfa.publicId]);}const filtered=await s.list(adminA,{search:"",city:"Recife",state:"PE",active:true,sort:"createdAt",direction:"desc",page:1,pageSize:1});expect(filtered).toMatchObject({total:1,page:1,pageSize:1,totalPages:1});expect(filtered.items[0].publicId).toBe(alfa.publicId);const ordered=await s.list(adminA,{search:"",sort:"legalName",direction:"asc",page:2,pageSize:1});expect(ordered).toMatchObject({total:2,page:2,pageSize:1,totalPages:2});expect(ordered.items[0].legalName).toBe("Zulu Razão");});
  it("19 publishes only after the inserted row is committed",async()=>{const events:string[]=[];const publisher:SupplierEventPublisher={publish:async clientId=>{expect(await count("SELECT COUNT(*) total FROM erp_suppliers WHERE client_id=?",[clientId])).toBe(1);events.push(clientId);}};await new SupplierService(new SupplierRepository(),publisher).create(adminA,input());expect(events).toEqual([adminA.clientId]);});
  it("20 emits nothing when the transaction rolls back",async()=>{const events:string[]=[];const publisher:SupplierEventPublisher={publish:clientId=>{events.push(clientId);}};const s=new SupplierService(new SupplierRepository(),publisher);const command=input();await s.create(adminA,command);await expect(s.create(adminA,{...input(),taxId:command.taxId})).rejects.toBeTruthy();expect(events).toEqual([adminA.clientId]);});
  it("21 scopes realtime publication to the changed tenant",async()=>{const events:string[]=[];const publisher:SupplierEventPublisher={publish:clientId=>{events.push(clientId);}};await new SupplierService(new SupplierRepository(),publisher).create(adminB,input());expect(events).toEqual([adminB.clientId]);expect(events).not.toContain(adminA.clientId);});
});
