import { useMemo, useState } from "react";
import { Activity, Download, ExternalLink, RefreshCw, Wrench } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const labels: Record<string, string> = { operational: "Operacional", attention: "Atenção", degraded: "Degradado", unavailable: "Indisponível", connected: "Conectado", disconnected: "Desconectado", connecting: "Conectando", qr_required: "QR necessário", provider_unavailable: "Provedor indisponível", webhook_degraded: "Webhook degradado", not_configured: "Não configurado", contracted: "Contratado", not_contracted: "Não contratado", pending: "Pendente" };
function badge(value: string) { const warning=["attention","connecting","pending","not_configured"].includes(value); const failure=["degraded","unavailable","provider_unavailable","webhook_degraded","disconnected"].includes(value); return `rounded-full border px-3 py-1 text-xs ${failure?"border-red-400/30 bg-red-400/10 text-red-200":warning?"border-amber-300/30 bg-amber-300/10 text-amber-100":"border-emerald-400/30 bg-emerald-400/10 text-emerald-100"}`; }
function flag(value: boolean | null) { return value===null?"não verificável":value?"conforme":"divergente"; }

export function PlatformHealthSection() {
  const health=trpc.megaadmin.platformHealth.useQuery(undefined,{refetchOnWindowFocus:false});
  const [selectedTenant,setSelectedTenant]=useState<string|null>(null); const [confirmRepair,setConfirmRepair]=useState(false);
  const tenant=trpc.megaadmin.tenantPlatformHealth.useQuery({clientId:selectedTenant??""},{enabled:Boolean(selectedTenant),refetchOnWindowFocus:false});
  const repair=trpc.megaadmin.platformRepairEvolution.useMutation({onSuccess:async result=>{setConfirmRepair(false);await Promise.all([health.refetch(),tenant.refetch()]);result.ok?toast.success("Reparo concluído e auditado."):toast.error("O reparo terminou com falha; consulte o histórico.");},onError:error=>toast.error(error.message)});
  const report=health.data?.report; const portfolio=health.data?.portfolio??[]; const selected=tenant.data;
  const selectedPortfolio=useMemo(()=>portfolio.find(item=>item.clientId===selectedTenant),[portfolio,selectedTenant]);
  const download=()=>{if(!health.data?.reportJson)return;const blob=new Blob([health.data.reportJson],{type:"application/json"});const href=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=href;anchor.download=`megadesk-health-${new Date().toISOString().replace(/[:.]/g,"-")}.json`;anchor.click();URL.revokeObjectURL(href);};
  if(health.isLoading)return <div role="status" aria-live="polite" className="rounded-3xl border border-white/10 p-8 text-slate-300">Verificando sinais seguros da plataforma…</div>;
  if(health.error||!report)return <div role="alert" className="rounded-3xl border border-red-400/30 bg-red-400/10 p-6 text-red-100">Não foi possível executar o diagnóstico. Nenhuma recuperação foi executada.</div>;
  return <section className="space-y-6" aria-labelledby="platform-health-title">
    <div className="flex flex-col gap-4 rounded-[2rem] border border-white/10 bg-slate-950/70 p-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm text-cyan-300">Infraestrutura global compartilhada</p><h3 id="platform-health-title" className="mt-1 text-2xl font-semibold text-white">Saúde da Plataforma</h3><p className="mt-2 text-sm text-slate-400">Diagnóstico read-only; não executa Connect, QR, logout ou envio.</p></div><div className="flex flex-wrap gap-2"><span className={badge(report.state)}>{labels[report.state]}</span><button onClick={()=>health.refetch()} disabled={health.isFetching} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-sm text-white disabled:opacity-50"><RefreshCw className="h-4 w-4"/>Executar diagnóstico</button><button onClick={download} className="inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950"><Download className="h-4 w-4"/>Baixar relatório sanitizado</button></div></div>
    <div aria-live="polite" className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><HealthCard title="MegaDesk" lines={[`Versão ${report.version}`,`Checkpoint ${report.checkpoint??"não informado"}`,`Local ${report.http.local?"disponível":"indisponível"}`,`App HTTP ${report.http.app.status??"sem resposta"}`,`Admin HTTP ${report.http.admin.status??"sem resposta"}`,`API HTTP ${report.http.api.status??"sem resposta"}`]}/><HealthCard title="Evolution compartilhada" lines={[`Provedor ${report.evolution.providerReachable?"com evidência disponível":"indisponível"}`,"Banco não verificável pela aplicação","Warnings e restart count não disponíveis",`Verificado ${new Date(report.timestamp).toLocaleString()}`]}/><HealthCard title="Configuração crítica" lines={[`Cache local ${flag(report.critical.localCacheDisabled)}`,`Redis ${flag(report.critical.redisDisabled)}`,`Preservação ${flag(report.critical.instancePreserved)}`,`Webhook autenticado ${flag(report.critical.webhookAuthenticated)}`]}/><HealthCard title="Backup" lines={["Não verificável pela aplicação","Backup externo ao repositório","Conteúdo e caminhos não expostos"]}/></div>
    <div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><div className="rounded-[2rem] border border-white/10 bg-slate-950/70 p-6"><h4 className="text-lg font-semibold text-white">Portfólio de tenants</h4><p className="mb-4 text-sm text-slate-400">Selecione um cliente autorizado para ver seu diagnóstico isolado.</p><div className="space-y-2">{portfolio.map(item=><button key={item.clientId} onClick={()=>setSelectedTenant(item.clientId)} className={`flex w-full items-center justify-between rounded-2xl border p-4 text-left ${selectedTenant===item.clientId?"border-cyan-400/50 bg-cyan-400/10":"border-white/10 bg-white/[.03]"}`}><span><strong className="block text-white">{item.company}</strong><span className="text-xs text-slate-400">{labels[item.contract]??item.contract}</span></span><span className={badge(item.integrationState)}>{labels[item.integrationState]??item.integrationState}</span></button>)}</div></div>
      <div className="rounded-[2rem] border border-white/10 bg-slate-950/70 p-6">{!selectedTenant?<p className="text-slate-400">Nenhum tenant selecionado.</p>:tenant.isLoading?<p role="status" className="text-slate-400">Carregando detalhe isolado…</p>:selected?<div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-cyan-300">Tenant selecionado</p><h4 className="text-xl font-semibold text-white">{selected.tenant.company}</h4><p className="text-sm text-slate-400">Módulos: {selected.tenant.modules.join(", ")||"nenhum"}</p></div><span className={badge(selected.integration.state)}>{labels[selected.integration.state]??selected.integration.state}</span></div><div className="grid gap-3 sm:grid-cols-2"><Mini title="Contrato" value={labels[selected.integration.contract]??selected.integration.contract}/><Mini title="Webhook" value={selected.integration.webhookEnabled===null?"Não aplicável":selected.integration.webhookEnabled?"Habilitado":"Degradado"}/><Mini title="Provedor" value={selected.integration.providerReachable===null?"Não aplicável":selected.integration.providerReachable?"Disponível":"Indisponível"}/><Mini title="Última atividade" value={selected.lastActivity?new Date(String(selected.lastActivity)).toLocaleString():"Sem evento auditado"}/></div><div><h5 className="mb-2 font-medium text-white">Histórico operacional</h5>{selected.history.length?<ul className="space-y-2">{selected.history.map((event,index)=><li key={`${event.operationId}-${index}`} className="rounded-xl border border-white/10 p-3 text-sm text-slate-300">{String(event.action)} · {auditLabel(event.eventPhase,event.success)} · {event.operationId??"sem ID"}</li>)}</ul>:<p className="text-sm text-slate-400">Nenhum evento operacional disponível.</p>}</div><div className="flex flex-wrap gap-2">{selected.actions.connect&&<a href="https://app.megadesk.online/whatsapp" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-sm text-white"><ExternalLink className="h-4 w-4"/>Ir para conectar</a>}{selected.actions.repair&&<button onClick={()=>setConfirmRepair(true)} disabled={repair.isPending} className="inline-flex items-center gap-2 rounded-xl bg-amber-300 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50"><Wrench className="h-4 w-4"/>Reparar integração</button>}</div></div>:<p role="alert" className="text-red-200">Falha ao carregar o tenant selecionado.</p>}</div></div>
    {confirmRepair&&selectedTenant&&<div role="dialog" aria-modal="true" aria-labelledby="repair-title" className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="max-w-lg rounded-3xl border border-amber-300/30 bg-slate-950 p-6"><h4 id="repair-title" className="text-xl font-semibold text-white">Confirmar reparo de {selectedPortfolio?.company}</h4><p className="mt-3 text-sm text-slate-300">A instância armazenada deste tenant será verificada e o webhook poderá ser reconfigurado. Sessão, instância e mensagens não serão apagadas; logout, QR e envio não serão executados.</p><div className="mt-5 flex justify-end gap-2"><button autoFocus onClick={()=>setConfirmRepair(false)} className="rounded-xl border border-white/10 px-4 py-2 text-white">Cancelar</button><button onClick={()=>repair.mutate({clientId:selectedTenant})} disabled={repair.isPending} className="rounded-xl bg-amber-300 px-4 py-2 font-semibold text-slate-950 disabled:opacity-50">{repair.isPending?"Reparando…":"Confirmar reparo"}</button></div></div></div>}
  </section>;
}
function HealthCard({title,lines}:{title:string;lines:string[]}){return <article className="rounded-3xl border border-white/10 bg-white/[.03] p-5"><div className="mb-3 flex items-center gap-2 text-white"><Activity className="h-5 w-5 text-cyan-300"/><h4 className="font-semibold">{title}</h4></div><ul className="space-y-2 text-sm text-slate-400">{lines.map(line=><li key={line}>{line}</li>)}</ul></article>}
function Mini({title,value}:{title:string;value:string}){return <div className="rounded-2xl border border-white/10 p-3"><p className="text-xs text-slate-500">{title}</p><p className="mt-1 text-sm text-white">{value}</p></div>}
function auditLabel(phase: string|null, success: boolean|null){if(phase==="intent"&&success===null)return "Em andamento";if(phase==="success"&&success===true)return "Concluído";if(phase==="failure"&&success===false)return "Falhou";if(phase===null)return success===false?"Falhou (legado)":"Concluído (legado)";return "Estado inconsistente";}
