import React from "react";
import { AlertCircle, RefreshCw, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";

type SupplierForm = {
  publicId?: string; legalName: string; tradeName: string; personType: "legal" | "individual"; taxId: string;
  stateRegistration: string; email: string; phone: string; contactName: string; postalCode: string; street: string;
  addressNumber: string; addressComplement: string; district: string; city: string; state: string; notes: string;
};
const emptySupplier: SupplierForm = { legalName: "", tradeName: "", personType: "legal", taxId: "", stateRegistration: "", email: "", phone: "", contactName: "", postalCode: "", street: "", addressNumber: "", addressComplement: "", district: "", city: "", state: "", notes: "" };

function StateMessage({ title, retry }: { title: string; retry?: () => void }) {
  return <div role="status" className="rounded-2xl border border-slate-200 bg-white p-8 text-center"><AlertCircle className="mx-auto mb-3 h-7 w-7 text-slate-400"/><p className="font-semibold text-slate-800">{title}</p>{retry&&<Button className="mt-4" variant="outline" onClick={retry}><RefreshCw className="mr-2 h-4 w-4"/>Tentar novamente</Button>}</div>;
}
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string,string][] }) {
  return <label className="text-sm"><span className="sr-only">{label}</span><select aria-label={label} className="w-full rounded-lg border p-2" value={value} onChange={event=>onChange(event.target.value)}>{options.map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>;
}
function Field({ label, value, onChange, required=false }: { label: string; value: string; onChange: (value:string)=>void; required?: boolean }) {
  return <label className="text-sm">{label}<Input required={required} className="mt-1" value={value} onChange={event=>onChange(event.target.value)}/></label>;
}

export function SuppliersPage() {
  const utils=trpc.useUtils();
  const [search,setSearch]=React.useState(""); const [active,setActive]=React.useState<"all"|"active"|"inactive">("all"); const [city,setCity]=React.useState(""); const [state,setState]=React.useState("");
  const [sort,setSort]=React.useState<"legalName"|"createdAt">("legalName"); const [direction,setDirection]=React.useState<"asc"|"desc">("asc"); const [page,setPage]=React.useState(1); const [pageSize,setPageSize]=React.useState(20);
  const [form,setForm]=React.useState<SupplierForm|null>(null); const [message,setMessage]=React.useState("");
  const query=trpc.erp.suppliers.list.useQuery({search,active:active==="all"?undefined:active==="active",city:city||undefined,state:state||undefined,sort,direction,page,pageSize});
  const refresh=async(text:string)=>{setForm(null);setMessage(text);await utils.erp.suppliers.invalidate();};
  const create=trpc.erp.suppliers.create.useMutation({onSuccess:()=>refresh("Fornecedor cadastrado com sucesso.")});
  const update=trpc.erp.suppliers.update.useMutation({onSuccess:()=>refresh("Fornecedor atualizado com sucesso.")});
  const status=trpc.erp.suppliers.setActive.useMutation({onSuccess:async()=>{setMessage("Status do fornecedor atualizado.");await utils.erp.suppliers.invalidate();}});
  const pending=create.isPending||update.isPending;
  const canWrite=query.data?.canWrite===true;
  const resetPage=()=>setPage(1);
  const reset=()=>{setSearch("");setActive("all");setCity("");setState("");setSort("legalName");setDirection("asc");setPage(1);};
  const edit=(supplier:NonNullable<typeof query.data>["items"][number])=>setForm({publicId:supplier.publicId,legalName:supplier.legalName,tradeName:supplier.tradeName??"",personType:supplier.personType,taxId:supplier.taxId??"",stateRegistration:supplier.stateRegistration??"",email:supplier.email??"",phone:supplier.phone??"",contactName:supplier.contactName??"",postalCode:supplier.postalCode??"",street:supplier.street??"",addressNumber:supplier.addressNumber??"",addressComplement:supplier.addressComplement??"",district:supplier.district??"",city:supplier.city??"",state:supplier.state??"",notes:supplier.notes??""});
  const submit=(event:React.FormEvent)=>{event.preventDefault();if(!form||pending)return;const {publicId,...input}=form;if(publicId)update.mutate({publicId,...input});else create.mutate(input);};
  const totalPages=query.data?.totalPages??0;
  return <div className="space-y-5" data-testid="erp-suppliers-page">
    <header className="flex flex-wrap items-end justify-between gap-3"><h1 className="text-2xl font-bold">Fornecedores</h1>{canWrite&&<Button onClick={()=>setForm({...emptySupplier})}>Novo fornecedor</Button>}</header>
    {message&&<p role="status" className="rounded-lg bg-blue-50 p-3 text-sm text-blue-800">{message}</p>}
    {query.data&&<section aria-label="Resumo de fornecedores" className="grid grid-cols-3 gap-3">{[["Total",query.data.total],["Ativos",query.data.activeCount],["Inativos",query.data.inactiveCount]].map(([label,value])=><article key={label} className="rounded-2xl border bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="text-xl font-bold">{value}</p></article>)}</section>}
    <section aria-label="Filtros de fornecedores" className="grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-2 xl:grid-cols-4">
      <label className="relative sm:col-span-2"><span className="sr-only">Pesquisar fornecedores</span><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input className="pl-9" value={search} onChange={e=>{setSearch(e.target.value);resetPage()}} placeholder="Razão social, nome, CPF/CNPJ ou e-mail"/></label>
      <Select label="Filtrar status" value={active} onChange={v=>{setActive(v as typeof active);resetPage()}} options={[["all","Todos"],["active","Ativos"],["inactive","Inativos"]]}/>
      <Input aria-label="Filtrar cidade" value={city} onChange={e=>{setCity(e.target.value);resetPage()}} placeholder="Cidade"/>
      <Input aria-label="Filtrar UF" value={state} maxLength={2} onChange={e=>{setState(e.target.value.toUpperCase());resetPage()}} placeholder="UF"/>
      <Select label="Ordenar fornecedores" value={sort} onChange={v=>{setSort(v as typeof sort);resetPage()}} options={[["legalName","Razão social"],["createdAt","Cadastro"]]}/>
      <Select label="Direção da ordenação" value={direction} onChange={v=>{setDirection(v as typeof direction);resetPage()}} options={[["asc","Crescente"],["desc","Decrescente"]]}/>
      <Select label="Itens por página" value={String(pageSize)} onChange={v=>{setPageSize(Number(v));resetPage()}} options={[["10","10 por página"],["20","20 por página"],["50","50 por página"]]}/><Button variant="outline" onClick={reset}>Limpar filtros</Button>
    </section>
    {query.isLoading?<StateMessage title="Carregando fornecedores…"/>:query.error?<StateMessage title={query.error.message||"Erro ao carregar fornecedores."} retry={()=>void query.refetch()}/>:query.data?.items.length===0?<StateMessage title={search||city||state||active!=="all"?"Nenhum fornecedor corresponde aos filtros.":"Nenhum fornecedor cadastrado."}/>:<>
      <div className="hidden overflow-x-auto rounded-2xl border bg-white md:block"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50"><tr>{["Fornecedor","CPF/CNPJ","Contato","Localidade","Status",...(canWrite?["Ações"]:[])].map(label=><th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{query.data?.items.map(item=><tr key={item.publicId} className="border-t"><td className="p-3 font-medium">{item.legalName}{item.tradeName&&<span className="block text-xs text-slate-500">{item.tradeName}</span>}</td><td className="p-3">{item.taxId??"—"}</td><td className="p-3">{item.contactName??item.email??item.phone??"—"}</td><td className="p-3">{[item.city,item.state].filter(Boolean).join(" / ")||"—"}</td><td className="p-3">{item.active?"Ativo":"Inativo"}</td>{canWrite&&<td className="p-3"><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>edit(item)}>Editar</Button><Button size="sm" variant="outline" disabled={status.isPending} onClick={()=>status.mutate({publicId:item.publicId,active:!item.active})}>{item.active?"Inativar":"Ativar"}</Button></div></td>}</tr>)}</tbody></table></div>
      <div className="grid gap-3 md:hidden">{query.data?.items.map(item=><article key={item.publicId} className="rounded-2xl border bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{item.legalName}</p><p className="text-xs text-slate-500">{item.tradeName??item.taxId??"Sem documento"}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{item.active?"Ativo":"Inativo"}</span></div><p className="mt-3 text-sm">{item.contactName??item.email??item.phone??"Sem contato"}</p><p className="text-sm text-slate-500">{[item.city,item.state].filter(Boolean).join(" / ")||"Localidade não informada"}</p>{canWrite&&<div className="mt-4 flex gap-2"><Button size="sm" variant="outline" onClick={()=>edit(item)}>Editar</Button><Button size="sm" variant="outline" onClick={()=>status.mutate({publicId:item.publicId,active:!item.active})}>{item.active?"Inativar":"Ativar"}</Button></div>}</article>)}</div>
    </>}
    {query.data&&<nav aria-label="Paginação de fornecedores" className="flex flex-wrap items-center justify-end gap-2"><span className="mr-auto text-sm text-slate-600">{query.data.total} fornecedor(es)</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>Anterior</Button><span className="text-sm">Página {page} de {Math.max(1,totalPages)}</span><Button variant="outline" disabled={page>=totalPages} onClick={()=>setPage(page+1)}>Próxima</Button></nav>}
    <Dialog open={Boolean(form)} onOpenChange={open=>!open&&setForm(null)}><DialogContent className="max-h-[90vh] overflow-y-auto bg-white sm:max-w-2xl"><DialogHeader><DialogTitle>{form?.publicId?"Editar fornecedor":"Novo fornecedor"}</DialogTitle></DialogHeader>{form&&<form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field required label="Razão social / nome" value={form.legalName} onChange={legalName=>setForm({...form,legalName})}/><Field label="Nome fantasia" value={form.tradeName} onChange={tradeName=>setForm({...form,tradeName})}/><Select label="Tipo de pessoa" value={form.personType} onChange={personType=>setForm({...form,personType:personType as SupplierForm["personType"]})} options={[["legal","Pessoa jurídica"],["individual","Pessoa física"]]}/><Field label={form.personType==="legal"?"CNPJ":"CPF"} value={form.taxId} onChange={taxId=>setForm({...form,taxId})}/><Field label="Inscrição estadual" value={form.stateRegistration} onChange={stateRegistration=>setForm({...form,stateRegistration})}/><Field label="E-mail" value={form.email} onChange={email=>setForm({...form,email})}/><Field label="Telefone" value={form.phone} onChange={phone=>setForm({...form,phone})}/><Field label="Contato" value={form.contactName} onChange={contactName=>setForm({...form,contactName})}/><Field label="CEP" value={form.postalCode} onChange={postalCode=>setForm({...form,postalCode})}/><Field label="Logradouro" value={form.street} onChange={street=>setForm({...form,street})}/><Field label="Número" value={form.addressNumber} onChange={addressNumber=>setForm({...form,addressNumber})}/><Field label="Complemento" value={form.addressComplement} onChange={addressComplement=>setForm({...form,addressComplement})}/><Field label="Bairro" value={form.district} onChange={district=>setForm({...form,district})}/><Field label="Cidade" value={form.city} onChange={city=>setForm({...form,city})}/><Field label="UF" value={form.state} onChange={state=>setForm({...form,state:state.toUpperCase()})}/><label className="text-sm sm:col-span-2">Observações<textarea className="mt-1 min-h-24 w-full rounded-lg border p-2" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{(create.error||update.error)&&<p role="alert" className="text-sm text-red-600 sm:col-span-2">{create.error?.message??update.error?.message}</p>}<div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="outline" onClick={()=>setForm(null)}>Cancelar</Button><Button type="submit" disabled={pending}>{pending?"Salvando…":"Salvar"}</Button></div></form>}</DialogContent></Dialog>
  </div>;
}
