import { expect, test, type BrowserContext, type Page } from "@playwright/test";
import bcrypt from "bcryptjs";
import mysql, { type Pool, type ResultSetHeader, type RowDataPacket } from "mysql2/promise";
import { validateTestDatabaseUrl } from "../server/test-integration-gates";
const enabled =
  process.env.RUN_DATABASE_INTEGRATION === "1" &&
  Boolean(process.env.TEST_DATABASE_URL && process.env.E2E_PASSWORD_A && process.env.E2E_PASSWORD_B);
const tenantA="reports-a",tenantB="reports-b",passwordA=process.env.E2E_PASSWORD_A,passwordB=process.env.E2E_PASSWORD_B;
const users={admin:"reports-admin-a@example.invalid",manager:"reports-manager-a@example.invalid",viewer:"reports-viewer-a@example.invalid",agent:"reports-agent-a@example.invalid",adminB:"reports-admin-b@example.invalid"};
let pool:Pool;
const contexts=new Set<BrowserContext>();
async function insert(sql:string,values:unknown[]=[]){const [r]=await pool.execute<ResultSetHeader>(sql,values);return r.insertId;}
async function verifySchema(){const required=["megadesk_domain_clients","megadesk_domain_client_users","megadesk_operational_sessions","megadesk_crm_clients","erp_products","erp_stock_balances","erp_stock_movements","erp_suppliers","erp_purchase_orders","erp_purchase_order_items","erp_sale_orders","erp_financial_accounts","erp_financial_categories","erp_financial_entries","erp_fiscal_settings","erp_fiscal_documents"];const [rows]=await pool.query<RowDataPacket[]>("SELECT table_name FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN (?)",[required]);const present=new Set(rows.map(row=>String(row.TABLE_NAME??row.table_name))),missing=required.filter(table=>!present.has(table));if(missing.length)throw new Error(`Schema fÃ­sico incompleto para RelatÃ³rios E2E: ${missing.join(", ")}`);}
async function cleanup(){const t=[tenantA,tenantB];for(const sql of [
  "DELETE x FROM erp_fiscal_operations x JOIN erp_fiscal_documents d ON d.id=x.fiscal_document_id WHERE d.client_id IN (?,?)","DELETE x FROM erp_fiscal_document_history x JOIN erp_fiscal_documents d ON d.id=x.fiscal_document_id WHERE d.client_id IN (?,?)","DELETE FROM erp_fiscal_document_items WHERE client_id IN (?,?)","DELETE FROM erp_fiscal_documents WHERE client_id IN (?,?)","DELETE FROM erp_product_fiscal_profiles WHERE client_id IN (?,?)","DELETE x FROM erp_fiscal_settings_history x JOIN erp_fiscal_settings s ON s.id=x.settings_id WHERE s.client_id IN (?,?)","DELETE FROM erp_fiscal_settings WHERE client_id IN (?,?)",
  "DELETE FROM erp_financial_ledger WHERE client_id IN (?,?)","DELETE FROM erp_financial_settlements WHERE client_id IN (?,?)","DELETE FROM erp_financial_entries WHERE client_id IN (?,?)","DELETE FROM erp_financial_categories WHERE client_id IN (?,?)","DELETE FROM erp_financial_accounts WHERE client_id IN (?,?)",
  "DELETE x FROM erp_sale_order_items x JOIN erp_sale_orders o ON o.id=x.sale_order_id WHERE o.client_id IN (?,?)","DELETE FROM erp_sale_orders WHERE client_id IN (?,?)","DELETE x FROM erp_purchase_order_items x JOIN erp_purchase_orders o ON o.id=x.purchase_order_id WHERE o.client_id IN (?,?)","DELETE FROM erp_purchase_orders WHERE client_id IN (?,?)","DELETE FROM erp_stock_movements WHERE client_id IN (?,?)","DELETE FROM erp_stock_balances WHERE client_id IN (?,?)","DELETE FROM erp_suppliers WHERE client_id IN (?,?)","DELETE FROM erp_products WHERE client_id IN (?,?)","DELETE FROM megadesk_crm_clients WHERE client_id IN (?,?)","DELETE FROM megadesk_operational_sessions WHERE client_id IN (?,?)","DELETE FROM megadesk_domain_client_users WHERE client_id IN (?,?)","DELETE FROM megadesk_domain_clients WHERE client_id IN (?,?)"] )await pool.execute(sql,t);}
async function close(context:BrowserContext){try{await context.close();}finally{contexts.delete(context);}}
async function cookie(context:BrowserContext){const c=(await context.cookies()).find(x=>x.name==="megadesk_session");if(!c)throw new Error("SessÃ£o real ausente");return `${c.name}=${c.value}`;}
async function trpc(context:BrowserContext,procedure:string,input:unknown,method:"get"|"post"="get"){const url=`/api/trpc/${procedure}${method==="get"?`?input=${encodeURIComponent(JSON.stringify({json:input}))}`:""}`;return method==="get"?context.request.get(url,{headers:{Cookie:await cookie(context)}}):context.request.post(url,{headers:{Cookie:await cookie(context),Origin:process.env.PLAYWRIGHT_BASE_URL!},data:{json:input}});}
async function fixtures(){
  await cleanup(); const [hashA,hashB]=await Promise.all([bcrypt.hash(passwordA!,8),bcrypt.hash(passwordB!,8)]);
  await pool.execute("INSERT INTO megadesk_domain_clients(client_id,internal_id,tenant_database_name,company,contact,phone,plan,status,status_type,access_released,api_token,modules_json,integrations_json) VALUES (?,'reports-int-a','reports_a','Reports A','Fixture','00000000000','Test','active','test',1,'reports-a','[\"erp\"]','{}'),(?,'reports-int-b','reports_b','Reports B','Fixture','00000000001','Test','active','test',1,'reports-b','[\"erp\"]','{}')",[tenantA,tenantB]);
  await pool.execute("INSERT INTO megadesk_domain_client_users(user_id,client_id,name,email,role,status,permissions_json,password_hash) VALUES ('reports-admin-a',?,'Reports Admin A',?,'admin','active','[\"erp\"]',?),('reports-manager-a',?,'Reports Manager A',?,'manager','active','[\"erp\"]',?),('reports-viewer-a',?,'Reports Viewer A',?,'viewer','active','[\"erp\"]',?),('reports-agent-a',?,'Reports Agent A',?,'agent','active','[\"erp\"]',?),('reports-admin-b',?,'Reports Admin B',?,'admin','active','[\"erp\"]',?)",[tenantA,users.admin,hashA,tenantA,users.manager,hashA,tenantA,users.viewer,hashA,tenantA,users.agent,hashA,tenantB,users.adminB,hashB]);
  await pool.execute("INSERT INTO megadesk_crm_clients(crm_client_id,client_id,company_name,status,created_at) VALUES ('ra-client-a',?,'Alpha Cliente','ativo','2026-08-02'),('ra-client-z',?,'Zulu Cliente','ativo','2026-08-03'),('rb-client',?,'SENTINELA CLIENTE B','ativo','2026-08-02')",[tenantA,tenantA,tenantB]);
  const pa=await insert("INSERT INTO erp_products(public_id,client_id,name,sku,unit,minimum_stock,active,created_by,created_at) VALUES ('ra-prod',?,'Alpha Produto','SKU-A','unit',5,1,'fixture','2026-08-01')",[tenantA]),pb=await insert("INSERT INTO erp_products(public_id,client_id,name,sku,unit,minimum_stock,active,created_by,created_at) VALUES ('rb-prod',?,'SENTINELA PRODUTO B','SKU-B','unit',0,1,'fixture','2026-08-01')",[tenantB]);
  await pool.execute("INSERT INTO erp_stock_balances(client_id,product_id,quantity) VALUES (?,?,2),(?,?,99)",[tenantA,pa,tenantB,pb]); await pool.execute("INSERT INTO erp_stock_movements(public_id,client_id,product_id,type,direction,quantity,previous_balance,resulting_balance,reason,idempotency_key,payload_hash,created_by,created_at) VALUES ('ra-move',?,?,'manual_in','in',2,0,2,'fixture','ra-move-key',REPEAT('a',64),'fixture','2026-08-04')",[tenantA,pa]);
  const sa=await insert("INSERT INTO erp_suppliers(public_id,client_id,legal_name,person_type,active,created_by,created_at) VALUES ('ra-sup',?,'Alpha Fornecedor','legal',1,'fixture','2026-08-02')",[tenantA]),sb=await insert("INSERT INTO erp_suppliers(public_id,client_id,legal_name,person_type,active,created_by,created_at) VALUES ('rb-sup',?,'SENTINELA FORNECEDOR B','legal',1,'fixture','2026-08-02')",[tenantB]);
  const po=await insert("INSERT INTO erp_purchase_orders(public_id,client_id,order_number,supplier_id,supplier_name_snapshot,status,subtotal_cents,total_cents,received_at,received_by,created_by,created_at) VALUES ('ra-po',?,'PO-001',?,'Alpha Fornecedor','received',6000,6000,'2026-08-05','fixture','fixture','2026-08-04')",[tenantA,sa]); await pool.execute("INSERT INTO erp_purchase_order_items(public_id,purchase_order_id,product_id,product_name_snapshot,sku_snapshot,quantity,unit_cost_cents,line_total_cents) VALUES ('ra-poi',?,?,'Alpha Produto','SKU-A',3,2000,6000)",[po,pa]);
  await pool.execute("INSERT INTO erp_purchase_orders(public_id,client_id,order_number,supplier_id,supplier_name_snapshot,status,subtotal_cents,total_cents,received_at,received_by,created_by,created_at) VALUES ('rb-po',?,'PO-B-001',?,'SENTINELA FORNECEDOR B','received',999999,999999,'2026-08-05','fixture','fixture','2026-08-04')",[tenantB,sb]);
  for(let i=1;i<=21;i++){const num=`SO-${String(i).padStart(3,"0")}`,fulfilled=i<=2;await pool.execute("INSERT INTO erp_sale_orders(public_id,client_id,order_number,crm_client_id,customer_name_snapshot,status,subtotal_cents,total_cents,fulfilled_at,fulfilled_by,created_by,created_at) VALUES (?,?,?,?,?,?,?, ?,?,IF(? IS NULL,NULL,'fixture'),'fixture',?)",[`ra-so-${i}`,tenantA,num,i%2?"ra-client-a":"ra-client-z",i===1?"=FORMULA Cliente":i%2?"Alpha Cliente":"Zulu Cliente",fulfilled?"fulfilled":"draft",fulfilled?i*1000:1,fulfilled?i*1000:1,fulfilled?`2026-08-0${i+3}`:null,fulfilled?`2026-08-0${i+3}`:null,`2026-08-${String(Math.min(i+1,9)).padStart(2,"0")}`]);}
  await pool.execute("INSERT INTO erp_sale_orders(public_id,client_id,order_number,crm_client_id,customer_name_snapshot,status,subtotal_cents,total_cents,fulfilled_at,fulfilled_by,created_by,created_at) VALUES ('ra-so-prev',?,'SO-PREV','ra-client-a','Alpha Cliente','fulfilled',1000,1000,'2026-07-25','fixture','fixture','2026-07-25'),('rb-so',?,'SO-B-001','rb-client','SENTINELA CLIENTE B','fulfilled',999999,999999,'2026-08-05','fixture','fixture','2026-08-04')",[tenantA,tenantB]);
  const aa=await insert("INSERT INTO erp_financial_accounts(public_id,client_id,name,type,initial_balance_cents,current_balance_cents,active,created_by) VALUES ('ra-account',?,'Conta A','bank',10000,13000,1,'fixture')",[tenantA]),ca=await insert("INSERT INTO erp_financial_categories(public_id,client_id,name,direction) VALUES ('ra-category',?,'Categoria A','both')",[tenantA]);
  await pool.execute("INSERT INTO erp_financial_entries(public_id,client_id,document_number,direction,status,description,amount_cents,due_date,issue_date,category_id,financial_account_id,source_type,party_name_snapshot,settled_at,settled_by,created_by) VALUES ('ra-fin-open',?,'FIN-001','receivable','open','fixture',3000,'2090-01-01','2026-08-05',?,NULL,'manual','Alpha Cliente',NULL,NULL,'fixture'),('ra-fin-settled',?,'FIN-002','receivable','settled','fixture',4500,'2026-08-05','2026-08-05',?,?,'manual','Zulu Cliente','2026-08-06','fixture','fixture')",[tenantA,ca,tenantA,ca,aa]);
  await pool.execute("INSERT INTO erp_fiscal_settings(public_id,client_id,tax_regime,taxpayer_indicator,status,updated_by) VALUES ('ra-settings',?,'simples_nacional','taxpayer','incomplete','fixture')",[tenantA]); await pool.execute("INSERT INTO erp_fiscal_documents(public_id,client_id,internal_number,type,status,internal_issue_date,party_name_snapshot,total_cents,created_by,updated_by) VALUES ('ra-fis',?,'FIS-001','manual','draft','2026-08-03','Manual A',1000,'fixture','fixture'),('rb-fis',?,'FIS-B-001','manual','draft','2026-08-03','SENTINELA FISCAL B',999999,'fixture','fixture')",[tenantA,tenantB]);
}
async function login(page: Page,email=users.admin,password=passwordA!,openReports=email!==users.agent) {
  await page.goto("/");
  await page.getByPlaceholder("seu@email.com").fill(email);
  await page.getByPlaceholder("Sua senha de acesso").fill(password);
  await page.getByRole("button", { name: "Entrar na plataforma" }).click();
  if ((page.viewportSize()?.width ?? 1024) < 1024)
    await page.getByRole("button", { name: "Abrir menu", exact: true }).click();
  await expect(page.getByRole("button", { name: "ERP", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "ERP", exact: true }).click();
  if(openReports){await page.getByTestId("erp-workspace").getByRole("button", { name: "Relatórios", exact: true }).click();await expect(page).toHaveURL(/\/erp\/relatorios$/);}
}
test.describe.serial("reports physical mysql", () => {
  test.skip(
    !enabled,
    "RUN_DATABASE_INTEGRATION e credencial física são obrigatórios."
  );
  test.beforeAll(async({request})=>{if(!process.env.TEST_DATABASE_URL||!passwordA||!passwordB||passwordA===passwordB)throw new Error("TEST_DATABASE_URL e duas senhas descartÃ¡veis distintas sÃ£o obrigatÃ³rias.");pool=mysql.createPool(validateTestDatabaseUrl(process.env.TEST_DATABASE_URL));await verifySchema();await fixtures();expect((await request.post("/api/trpc/megaadmin.logoutAdmin",{data:{json:null}})).status()).toBe(200);},60000);
  test.afterEach(async()=>{await Promise.allSettled([...contexts].map(close));});
  test.afterAll(async()=>{try{await cleanup();}finally{await pool.end();}});
  test("admin usa dados MySQL reais, filtros, paginação, ordenação e CSV", async ({browser}) => {
    const context=await browser.newContext({viewport:{width:1440,height:900}});contexts.add(context);const page=await context.newPage();await login(page);
    await expect(page.getByRole("heading", { name: "Relatórios essenciais" })).toBeVisible();
    await page.getByLabel("Data inicial").fill("2026-08-01");await page.getByLabel("Data final").fill("2026-08-10");
    const reportTabs=page.getByRole("navigation",{name:"Seções de relatórios"});
    await expect(page.getByText("R$ 30,00").first()).toBeVisible();await expect(page.getByText("200%",{exact:true})).toBeVisible();
    for (const label of [
      "Resumo executivo",
      "Vendas",
      "Compras",
      "Estoque",
      "Financeiro",
      "Clientes",
      "Fornecedores",
      "Fiscal interno",
    ]) {
      await reportTabs.getByRole("button", { name: label, exact: true }).click();
      await expect(page.getByTestId("erp-reports-page")).toBeVisible();
    }
    await reportTabs.getByRole("button",{name:"Vendas",exact:true}).click();await page.getByLabel("Estado").selectOption("fulfilled");await expect(page.getByRole("cell",{name:"SO-001",exact:true})).toBeVisible();await expect(page.getByRole("cell",{name:"SO-003",exact:true})).toHaveCount(0);
    await reportTabs.getByRole("button",{name:"Estoque",exact:true}).click();await expect(page.getByLabel("Estado")).toHaveCount(0);await reportTabs.getByRole("button",{name:"Vendas",exact:true}).click();
    const input={section:"sales",from:"2026-08-01",to:"2026-08-10",page:1,pageSize:2,sort:"number",direction:"asc"};const asc=await trpc(context,"erp.reports.report",input);expect(asc.status()).toBe(200);expect(await asc.text()).toContain('"SO-001"');const desc=await trpc(context,"erp.reports.report",{...input,direction:"desc"});expect(await desc.text()).toContain('"SO-021"');const page2=await trpc(context,"erp.reports.report",{...input,page:2});const body=await page2.text();expect(body).toContain('"page":2');expect(body).toContain('"total":21');expect(body).toContain('"totalPages":11');expect(body).toContain('"SO-003"');
    await page.getByLabel("Estado").selectOption("");const download=page.waitForEvent("download");await page.getByRole("button",{name:"Exportar CSV"}).click();const artifact=await download;expect(artifact.suggestedFilename()).toBe("megadesk-sales-2026-08-01-2026-08-10.csv");const stream=await artifact.createReadStream();let csv="";for await(const chunk of stream)csv+=chunk.toString();expect(csv).toContain("'=FORMULA Cliente");expect(csv).not.toMatch(/client_id|cpf_cnpj|email|phone|address|observations/i);
    let failed=false;await page.route("**/api/trpc/erp.reports.report*",async route=>{if(!failed){failed=true;await route.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:{json:{message:"Falha controlada",code:-32603,data:{code:"INTERNAL_SERVER_ERROR",httpStatus:500}}}})});}else await route.continue();});await page.getByLabel("Data inicial").fill("2026-08-02");await expect(page.getByRole("button",{name:"Tentar novamente"})).toBeVisible();await page.unroute("**/api/trpc/erp.reports.report*");const real=page.waitForResponse(r=>r.url().includes("erp.reports.report")&&r.status()===200);await page.getByRole("button",{name:"Tentar novamente"}).click();await real;await expect(page.getByRole("cell",{name:"SO-021",exact:true})).toBeVisible();await page.reload();await expect(page).toHaveURL(/\/erp\/relatorios$/);await close(context);
  });
  test("roles, isolamento, sessão, tenant e quatro viewports são reais", async ({ browser }) => {
    for(const [email,role,canExport] of [[users.manager,"manager",true],[users.viewer,"viewer",false],[users.agent,"agent",false]] as const){const context=await browser.newContext();contexts.add(context);const page=await context.newPage();let reportRequests=0;page.on("request",r=>{if(r.url().includes("erp.reports"))reportRequests++;});await login(page,email,passwordA!);if(role==="agent"){await page.goto("/erp/relatorios");await expect(page).not.toHaveURL(/\/erp\/relatorios$/);await expect(page.getByTestId("erp-reports-page")).toHaveCount(0);expect(reportRequests).toBe(0);}else{await expect(page.getByTestId("erp-reports-page")).toBeVisible();expect(await page.getByRole("button",{name:"Exportar CSV"}).count()).toBe(canExport?1:0);}const response=await trpc(context,"erp.reports.exportCsv",{section:"sales",from:"2026-08-01",to:"2026-08-10",page:1,pageSize:20,sort:"date",direction:"desc",maxRows:100},"post");expect(response.status()).toBe(canExport?200:403);await close(context);}
    const b=await browser.newContext();contexts.add(b);const pageB=await b.newPage();await login(pageB,users.adminB,passwordB!);const rb=await trpc(b,"erp.reports.report",{section:"sales",from:"2026-08-01",to:"2026-08-10",page:1,pageSize:20,sort:"date",direction:"desc"});const bodyB=await rb.text();expect(bodyB).toContain("SENTINELA CLIENTE B");expect(bodyB).not.toMatch(/Alpha Cliente|Zulu Cliente|SO-001/);const cross=await trpc(b,"erp.reports.report",{section:"sales",from:"2026-08-01",to:"2026-08-10",publicId:"ra-client-a",page:1,pageSize:20,sort:"date",direction:"desc"});expect(await cross.text()).toContain('"total":0');await close(b);
    const revoked=await browser.newContext();contexts.add(revoked);const revokedPage=await revoked.newPage();await login(revokedPage);const revokedCookie=await cookie(revoked);await pool.execute("UPDATE megadesk_operational_sessions SET revoked_at=NOW() WHERE client_id=? AND revoked_at IS NULL",[tenantA]);expect((await revoked.request.get(`/api/trpc/erp.reports.report?input=${encodeURIComponent(JSON.stringify({json:{section:"sales",from:"2026-08-01",to:"2026-08-10",page:1,pageSize:20,sort:"date",direction:"desc"}}))}`,{headers:{Cookie:revokedCookie}})).status()).toBe(401);await close(revoked);
    const paused=await browser.newContext();contexts.add(paused);const pausedPage=await paused.newPage();await login(pausedPage);const pausedCookie=await cookie(paused);await pool.execute("UPDATE megadesk_domain_clients SET status='paused' WHERE client_id=?",[tenantA]);expect((await paused.request.get(`/api/trpc/erp.reports.report?input=${encodeURIComponent(JSON.stringify({json:{section:"sales",from:"2026-08-01",to:"2026-08-10",page:1,pageSize:20,sort:"date",direction:"desc"}}))}`,{headers:{Cookie:pausedCookie}})).status()).toBe(401);await pool.execute("UPDATE megadesk_domain_clients SET status='active',access_released=1 WHERE client_id=?",[tenantA]);await close(paused);
    for (const viewport of [
      { width: 390, height: 844 },
      { width: 768, height: 1024 },
      { width: 1024, height: 768 },
      { width: 1440, height: 900 },
    ]) {
      const context=await browser.newContext({viewport});contexts.add(context);const page=await context.newPage();await login(page);await page.goto("/erp/relatorios");await expect(page.getByTestId("erp-reports-page")).toBeVisible();const dimensions=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth<=document.documentElement.clientWidth,main:document.querySelector("main")?.getBoundingClientRect().right??Infinity,width:window.innerWidth}));expect(dimensions.overflow).toBe(true);expect(dimensions.main).toBeLessThanOrEqual(dimensions.width);await expect(page.getByRole("navigation",{name:"Seções de relatórios"})).toBeVisible();await expect(page.getByRole("button",{name:"Integrações"})).toBeDisabled();await close(context);
    }
  });
});
