import { expect, test, type Page } from "@playwright/test";

const report={schemaVersion:1,timestamp:"2026-08-29T12:00:00.000Z",correlationId:"00000000-0000-4000-8000-000000000001",version:"1.0.0",checkpoint:"c0e0f33",state:"attention",http:{local:true,app:{reachable:true,status:200,latencyMs:10},admin:{reachable:true,status:200,latencyMs:11},api:{reachable:true,status:404,latencyMs:9}},evolution:{providerReachable:true,expectedInstances:0,foundInstances:0,states:[],webhookEnabled:true,canonicalEventsComplete:true,consecutiveWebhookFailures:0,warningCounts:{prisma:0,lid:0},restartCount:null},critical:{localCacheDisabled:true,redisDisabled:true,instancePreserved:true,webhookAuthenticated:true},backup:{verifiableByApplication:false,externalToRepository:true},warnings:["BACKUP_NOT_VERIFIABLE_BY_APPLICATION"],failures:[],recommendations:[]};
const portfolio=[{clientId:"tenant-a",company:"Empresa Operacional",modules:["conversas"],contract:"contracted",integrationState:"connected",alertCount:0},{clientId:"tenant-b",company:"Empresa sem WhatsApp",modules:["erp"],contract:"not_contracted",integrationState:"not_configured",alertCount:0}];

async function prepare(page:Page){
  await page.addInitScript(()=>localStorage.setItem("megadesk-session-token",`controlled.${btoa(JSON.stringify({exp:Math.floor(Date.now()/1000)+3600}))}.signature`));
  let mutations=0;
  await page.route("**/api/trpc/**",async route=>{const url=route.request().url();const names=decodeURIComponent(new URL(url).pathname).replace(/^.*\/api\/trpc\//,"").split(",");if(route.request().method()==="POST")mutations++;
    const value=(name:string)=>name.includes("auth.me")?{user:{id:1,name:"Admin",email:"admin@example.test",role:"admin"}}:name.includes("megaadmin.summary")?{clients:[],totals:{clients:2,released:2,paused:0,conversations:0,tickets:0},auditLogs:[],operationalRecords:[]}:name.includes("megaadmin.platformHealth")?{report,reportJson:JSON.stringify(report),portfolio,thresholds:{lid:3,webhookFailures:3,restartLoop:3},evidence:{}}:name.includes("megaadmin.tenantPlatformHealth")?{tenant:{clientId:"tenant-b",company:"Empresa sem WhatsApp",modules:["erp"]},integration:{contract:"not_contracted",state:"not_configured",providerReachable:null,webhookEnabled:null,canonicalEventsComplete:null},lastActivity:null,alerts:[],history:[],actions:{repair:false,connect:false}}:null;
    const payload=names.map(name=>({result:{data:{json:value(name)}}}));await route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(new URL(url).searchParams.get("batch")==="1"?payload:payload[0])});});
  await page.goto("/admin"); return ()=>mutations;
}

test("health is responsive and keeps tenant states isolated without mutations",async({page})=>{const mutations=await prepare(page);for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1024,height:768},{width:1440,height:900}]){await page.setViewportSize(viewport);if(viewport.width<1280){await page.getByRole("button",{name:"Menu"}).click();await page.getByRole("button",{name:"Saúde da Plataforma"}).click();}else{await page.getByRole("button",{name:"Saúde da Plataforma"}).click();}await expect(page.getByRole("heading",{name:"Saúde da Plataforma",level:3})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(viewport.width);}
  await expect(page.getByText("Empresa Operacional")).toBeVisible();await expect(page.getByText("Empresa sem WhatsApp")).toBeVisible();await page.getByRole("button",{name:/Empresa sem WhatsApp/}).click();await expect(page.getByText("Não contratado").last()).toBeVisible();await expect(page.getByRole("button",{name:"Reparar integração"})).toHaveCount(0);expect(mutations()).toBe(0);});

test("keyboard focus reaches diagnostic and sanitized download actions",async({page})=>{await prepare(page);await page.setViewportSize({width:1440,height:900});await page.getByRole("button",{name:"Saúde da Plataforma"}).click();const diagnostic=page.getByRole("button",{name:"Executar diagnóstico"});await diagnostic.focus();await expect(diagnostic).toBeFocused();await diagnostic.press("Enter");await expect(page.getByRole("button",{name:"Baixar relatório sanitizado"})).toBeVisible();expect(await page.locator('[aria-live="polite"]').count()).toBeGreaterThanOrEqual(1);});
