import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import type { RowDataPacket } from "mysql2/promise";
import { applyCanonicalMigrations, MAIN_MIGRATIONS_DIR } from "../../_core/canonical-migrations";
import { getPool } from "../../db";
import { getTestDatabaseUrl, isTestDatabaseEnabled } from "../../test-integration-gates";
import { ErpRepository } from "./repository";
import { ErpService, type ErpEventPublisher } from "./service";

const physical = describe.runIf(isTestDatabaseEnabled());
const adminA={clientId:"erp-matrix-a",userId:"admin-a",role:"admin" as const};
const adminB={clientId:"erp-matrix-b",userId:"admin-b",role:"admin" as const};
const viewerA={clientId:"erp-matrix-a",userId:"viewer-a",role:"viewer" as const};
const agentA={clientId:"erp-matrix-a",userId:"agent-a",role:"agent" as const};
const base={name:"Produto matriz",sku:"MATRIX",barcode:null,description:null,category:"Matriz",unit:"unit" as const,costPriceCents:1234,salePriceCents:2345,minimumStock:"2"};
let serial=0;
const sku=()=>`MATRIX-${++serial}`;
const command=(overrides:Partial<typeof base>={})=>({...base,sku:sku(),...overrides});
async function clean(){await getPool().execute("DELETE FROM erp_stock_movements WHERE client_id IN (?,?)",[adminA.clientId,adminB.clientId]);await getPool().execute("DELETE FROM erp_stock_balances WHERE client_id IN (?,?)",[adminA.clientId,adminB.clientId]);await getPool().execute("DELETE FROM erp_products WHERE client_id IN (?,?)",[adminA.clientId,adminB.clientId]);}
async function count(sql:string,values:unknown[]=[]){const [rows]=await getPool().execute<RowDataPacket[]>(sql,values);return Number(rows[0]?.total??0);}
async function product(service:ErpService,identity=adminA,overrides:Partial<typeof base>={}){return service.createProduct(identity,command(overrides));}
async function stocked(service:ErpService,quantity="10",identity=adminA){const item=await product(service,identity);await service.moveStock(identity,{productPublicId:item.publicId,type:"manual_in",quantity,reason:"Saldo inicial",idempotencyKey:crypto.randomUUID()});return item;}

physical("ERP MySQL individually named behavior matrix",()=>{
  beforeAll(async()=>{await applyCanonicalMigrations(getTestDatabaseUrl(),MAIN_MIGRATIONS_DIR);});
  beforeEach(clean);afterAll(clean);

  describe("products",()=>{
    it("01 creates a product",async()=>{expect((await product(new ErpService())).publicId).toBeTruthy();});
    it("02 normalizes SKU",async()=>{expect((await product(new ErpService(),adminA,{sku:"  sku spaced  "})).sku).toBe("SKU-SPACED");});
    it("03 rejects duplicate SKU in one tenant",async()=>{const s=new ErpService();const c=command();await s.createProduct(adminA,c);await expect(s.createProduct(adminA,c)).rejects.toMatchObject({code:"CONFLICT"});});
    it("04 permits the same SKU in another tenant",async()=>{const s=new ErpService();const c=command();expect((await Promise.all([s.createProduct(adminA,c),s.createProduct(adminB,c)]))[1].sku).toBe(c.sku);});
    it("05 persists empty barcode as NULL",async()=>{expect((await product(new ErpService(),adminA,{barcode:"  "})).barcode).toBeNull();});
    it("06 rejects duplicate barcode in one tenant",async()=>{const s=new ErpService();await product(s,adminA,{barcode:"789000000001"});await expect(product(s,adminA,{barcode:"789000000001"})).rejects.toMatchObject({code:"CONFLICT"});});
    it("07 permits equal barcode in another tenant",async()=>{const s=new ErpService();await product(s,adminA,{barcode:"789000000002"});expect((await product(s,adminB,{barcode:"789000000002"})).barcode).toBe("789000000002");});
    it("08 edits a product",async()=>{const s=new ErpService();const item=await product(s);expect((await s.updateProduct(adminA,item.publicId,{...command(),name:"Produto editado"})).name).toBe("Produto editado");});
    it("09 deactivates without deleting",async()=>{const s=new ErpService();const item=await product(s);await s.setProductActive(adminA,item.publicId,false);expect((await s.getProduct(adminA,item.publicId)).active).toBe(false);});
    it("10 rejects cross-tenant detail access",async()=>{const s=new ErpService();const item=await product(s);await expect(s.getProduct(adminB,item.publicId)).rejects.toMatchObject({code:"NOT_FOUND"});});
    it("11 allows admin writes",async()=>{expect((await product(new ErpService())).active).toBe(true);});
    it("12 rejects viewer writes",async()=>{await expect(product(new ErpService(),viewerA)).rejects.toMatchObject({code:"FORBIDDEN"});});
    it("13 paginates server-side",async()=>{const s=new ErpService();for(let i=0;i<3;i++)await product(s);const list=await s.listProducts(adminA,{search:"",stock:"all",sort:"name",direction:"asc",page:2,pageSize:2});expect(list.items).toHaveLength(1);expect(list.totalPages).toBe(2);});
    it("14 combines tenant-aware search and filters",async()=>{const s=new ErpService();await product(s,adminA,{name:"Alvo busca",category:"Especial"});await product(s,adminB,{name:"Alvo busca",category:"Especial"});const list=await s.listProducts(adminA,{search:"Alvo",category:"Especial",active:true,stock:"empty",sort:"name",direction:"asc",page:1,pageSize:20});expect(list.total).toBe(1);});
    it("15 preserves monetary cents exactly",async()=>{const item=await product(new ErpService(),adminA,{costPriceCents:1999,salePriceCents:2999});expect([item.costPriceCents,item.salePriceCents]).toEqual([1999,2999]);});
  });

  describe("stock",()=>{
    it("16 input creates ledger and balance",async()=>{const s=new ErpService();const item=await stocked(s,"3");expect((await s.getProduct(adminA,item.publicId)).quantity).toBe("3.000");expect((await s.listMovements(adminA,{search:"",productPublicId:item.publicId,page:1,pageSize:20})).total).toBe(1);});
    it("17 output reduces balance",async()=>{const s=new ErpService();const item=await stocked(s);await s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_out",quantity:"2",reason:"Saida",idempotencyKey:crypto.randomUUID()});expect((await s.getProduct(adminA,item.publicId)).quantity).toBe("8.000");});
    it("18 positive adjustment increases balance",async()=>{const s=new ErpService();const item=await stocked(s,"1");await s.moveStock(adminA,{productPublicId:item.publicId,type:"adjustment_in",quantity:"2",reason:"Ajuste",idempotencyKey:crypto.randomUUID()});expect((await s.getProduct(adminA,item.publicId)).quantity).toBe("3.000");});
    it("19 negative adjustment reduces balance",async()=>{const s=new ErpService();const item=await stocked(s,"3");await s.moveStock(adminA,{productPublicId:item.publicId,type:"adjustment_out",quantity:"1",reason:"Ajuste",idempotencyKey:crypto.randomUUID()});expect((await s.getProduct(adminA,item.publicId)).quantity).toBe("2.000");});
    it("20 records previous and resulting balances",async()=>{const s=new ErpService();const item=await stocked(s,"4");const movement=await s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_out",quantity:"1",reason:"Saida",idempotencyKey:crypto.randomUUID()});expect([movement.previousBalance,movement.resultingBalance]).toEqual(["4.000","3.000"]);});
    it("21 preserves three decimal places",async()=>{const s=new ErpService();const item=await stocked(s,"1.234");expect((await s.getProduct(adminA,item.publicId)).quantity).toBe("1.234");});
    it("22 rejects precision above three decimals",async()=>{const {stockMovementInput}=await import("./contracts");expect(stockMovementInput.safeParse({productPublicId:crypto.randomUUID(),type:"manual_in",quantity:"1.2345",reason:"Teste",idempotencyKey:crypto.randomUUID()}).success).toBe(false);expect(await count("SELECT COUNT(*) total FROM erp_stock_movements WHERE client_id=?",[adminA.clientId])).toBe(0);});
    it("23 rejects output above balance",async()=>{const s=new ErpService();const item=await stocked(s,"1");await expect(s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_out",quantity:"2",reason:"Saida",idempotencyKey:crypto.randomUUID()})).rejects.toMatchObject({code:"INSUFFICIENT_STOCK"});});
    it("24 failed output creates no ledger",async()=>{const s=new ErpService();const item=await product(s);await expect(s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_out",quantity:"1",reason:"Saida",idempotencyKey:crypto.randomUUID()})).rejects.toBeTruthy();expect(await count("SELECT COUNT(*) total FROM erp_stock_movements WHERE client_id=?",[adminA.clientId])).toBe(0);});
    it("25 failed output leaves balance unchanged",async()=>{const s=new ErpService();const item=await stocked(s,"1");await expect(s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_out",quantity:"2",reason:"Saida",idempotencyKey:crypto.randomUUID()})).rejects.toBeTruthy();expect((await s.getProduct(adminA,item.publicId)).quantity).toBe("1.000");});
    it("26 requires a reason by contract",async()=>{const {stockMovementInput}=await import("./contracts");expect(stockMovementInput.safeParse({productPublicId:crypto.randomUUID(),type:"manual_in",quantity:"1",reason:"",idempotencyKey:crypto.randomUUID()}).success).toBe(false);expect(await count("SELECT COUNT(*) total FROM erp_stock_movements")).toBe(0);});
    it("27 rejects cross-tenant product movement",async()=>{const s=new ErpService();const item=await product(s);await expect(s.moveStock(adminB,{productPublicId:item.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:crypto.randomUUID()})).rejects.toMatchObject({code:"NOT_FOUND"});});
    it("28 rejects movements on inactive products",async()=>{const s=new ErpService();const item=await product(s);await s.setProductActive(adminA,item.publicId,false);await expect(s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:crypto.randomUUID()})).rejects.toMatchObject({code:"INACTIVE_PRODUCT"});});
    it("29 exposes no movement update service method",async()=>{const s=new ErpService();expect("updateMovement" in s).toBe(false);expect(await count("SELECT COUNT(*) total FROM erp_stock_movements")).toBe(0);});
    it("30 exposes no movement delete service method",async()=>{const s=new ErpService();expect("deleteMovement" in s).toBe(false);expect(await count("SELECT COUNT(*) total FROM erp_stock_movements")).toBe(0);});
  });

  describe("idempotency",()=>{
    it("31 identical key and payload does not duplicate",async()=>{const s=new ErpService();const item=await product(s);const key=crypto.randomUUID();for(let i=0;i<2;i++)await s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:key});expect(await count("SELECT COUNT(*) total FROM erp_stock_movements WHERE client_id=?",[adminA.clientId])).toBe(1);});
    it("32 replay returns the previous result",async()=>{const s=new ErpService();const item=await product(s);const key=crypto.randomUUID();const a=await s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:key});const b=await s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:key});expect(b.publicId).toBe(a.publicId);});
    it("33 same key with different payload fails",async()=>{const s=new ErpService();const item=await product(s);const key=crypto.randomUUID();await s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:key});await expect(s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_in",quantity:"2",reason:"Entrada",idempotencyKey:key})).rejects.toMatchObject({code:"IDEMPOTENCY_CONFLICT"});});
    it("34 same key is tenant-scoped",async()=>{const s=new ErpService();const [a,b]=await Promise.all([product(s,adminA),product(s,adminB)]);const key=crypto.randomUUID();await Promise.all([s.moveStock(adminA,{productPublicId:a.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:key}),s.moveStock(adminB,{productPublicId:b.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:key})]);expect(await count("SELECT COUNT(*) total FROM erp_stock_movements WHERE idempotency_key=?",[key])).toBe(2);});
    it("35 concurrent double click creates one movement",async()=>{const s=new ErpService();const item=await product(s);const key=crypto.randomUUID();const results=await Promise.allSettled([1,2].map(()=>s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:key})));expect(results.filter(x=>x.status==="fulfilled")).toHaveLength(2);expect(await count("SELECT COUNT(*) total FROM erp_stock_movements WHERE idempotency_key=?",[key])).toBe(1);});
    it("36 retry after a lost response does not duplicate",async()=>{const s=new ErpService();const item=await product(s);const key=crypto.randomUUID();await s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:key});const retry=await s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:key});expect(retry.resultingBalance).toBe("1.000");});
  });

  describe("concurrency",()=>{
    it("37 two simultaneous inputs produce the correct balance",async()=>{const s=new ErpService();const item=await product(s);await Promise.all([1,2].map(()=>s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:crypto.randomUUID()})));expect((await s.getProduct(adminA,item.publicId)).quantity).toBe("2.000");});
    it("38 two valid simultaneous outputs produce the correct balance",async()=>{const s=new ErpService();const item=await stocked(s,"2");await Promise.all([1,2].map(()=>s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_out",quantity:"1",reason:"Saida",idempotencyKey:crypto.randomUUID()})));expect((await s.getProduct(adminA,item.publicId)).quantity).toBe("0.000");});
    it("39 competing outputs confirm only the possible operation",async()=>{const s=new ErpService();const item=await stocked(s,"1");const results=await Promise.allSettled([1,2].map(()=>s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_out",quantity:"1",reason:"Saida",idempotencyKey:crypto.randomUUID()})));expect(results.filter(x=>x.status==="fulfilled")).toHaveLength(1);});
    it("40 never persists a negative balance",async()=>{const s=new ErpService();const item=await stocked(s,"1");await Promise.allSettled([1,2,3].map(()=>s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_out",quantity:"1",reason:"Saida",idempotencyKey:crypto.randomUUID()})));expect(await count("SELECT COUNT(*) total FROM erp_stock_balances WHERE quantity<0")).toBe(0);});
    it("41 has no ledger without corresponding balance",async()=>{const s=new ErpService();await stocked(s,"1");expect(await count("SELECT COUNT(*) total FROM erp_stock_movements m LEFT JOIN erp_stock_balances b ON b.client_id=m.client_id AND b.product_id=m.product_id WHERE b.product_id IS NULL")).toBe(0);});
    it("42 has no changed balance without ledger",async()=>{const s=new ErpService();await stocked(s,"1");expect(await count("SELECT COUNT(*) total FROM erp_stock_balances b LEFT JOIN erp_stock_movements m ON m.client_id=b.client_id AND m.product_id=b.product_id WHERE b.quantity<>0 AND m.id IS NULL")).toBe(0);});
    it("43 classifies deadlocks as retryable",async()=>{const {isRetryableStockError}=await import("./service");expect(isRetryableStockError({code:"ER_LOCK_DEADLOCK"})).toBe(true);expect(await count("SELECT COUNT(*) total FROM erp_products")).toBe(0);});
    it("44 classifies lock timeouts as retryable",async()=>{const {isRetryableStockError}=await import("./service");expect(isRetryableStockError({code:"ER_LOCK_WAIT_TIMEOUT"})).toBe(true);expect(await count("SELECT COUNT(*) total FROM erp_products")).toBe(0);});
    it("45 does not retry permanent conflicts",async()=>{const {isRetryableStockError}=await import("./service");expect(isRetryableStockError({code:"ER_DUP_ENTRY"})).toBe(false);expect(await count("SELECT COUNT(*) total FROM erp_products")).toBe(0);});
  });

  describe("rollback and post-commit",()=>{
    it("46 rolls back a failure before ledger",async()=>{const s=new ErpService();const item=await product(s);await expect(s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_out",quantity:"1",reason:"Saida",idempotencyKey:crypto.randomUUID()})).rejects.toBeTruthy();expect(await count("SELECT COUNT(*) total FROM erp_stock_movements")).toBe(0);});
    it("47 rolls back ledger and balance together",async()=>{const connection=await getPool().getConnection();try{await connection.beginTransaction();const item=await product(new ErpService());await connection.execute("UPDATE erp_stock_balances SET quantity=9 WHERE client_id=? AND product_id=(SELECT id FROM erp_products WHERE public_id=?)",[adminA.clientId,item.publicId]);await connection.rollback();expect((await new ErpService().getProduct(adminA,item.publicId)).quantity).toBe("0.000");}finally{connection.release();}});
    it("48 uncommitted changes are invisible",async()=>{const c=await getPool().getConnection();try{await c.beginTransaction();await c.execute("INSERT INTO erp_products(public_id,client_id,name,sku,unit,cost_price_cents,sale_price_cents,minimum_stock,active,created_by) VALUES(?,?,?,?,?,0,0,0,1,?)",[crypto.randomUUID(),adminA.clientId,"Pending",sku(),"unit",adminA.userId]);expect(await count("SELECT COUNT(*) total FROM erp_products WHERE client_id=?",[adminA.clientId])).toBe(0);await c.rollback();}finally{c.release();}});
    it("49 publisher failure does not undo committed product",async()=>{const publisher:ErpEventPublisher={publish:()=>{throw new Error("offline")}};const s=new ErpService(new ErpRepository(),undefined,publisher);expect((await product(s)).publicId).toBeTruthy();expect(await count("SELECT COUNT(*) total FROM erp_products WHERE client_id=?",[adminA.clientId])).toBe(1);});
    it("50 publisher failure does not return a misleading stock error",async()=>{const publisher:ErpEventPublisher={publish:()=>{throw new Error("offline")}};const s=new ErpService(new ErpRepository(),undefined,publisher);const item=await product(s);expect((await s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:crypto.randomUUID()})).resultingBalance).toBe("1.000");});
    it("51 retry after publisher failure does not duplicate",async()=>{const publisher:ErpEventPublisher={publish:()=>{throw new Error("offline")}};const s=new ErpService(new ErpRepository(),undefined,publisher);const item=await product(s);const key=crypto.randomUUID();await s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:key});await s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_in",quantity:"1",reason:"Entrada",idempotencyKey:key});expect(await count("SELECT COUNT(*) total FROM erp_stock_movements WHERE idempotency_key=?",[key])).toBe(1);});
  });

  describe("reversal",()=>{
    it("52 reversal creates a new ledger row",async()=>{const s=new ErpService();const item=await stocked(s,"2");const first=(await s.listMovements(adminA,{search:"",productPublicId:item.publicId,page:1,pageSize:20})).items[0];await s.reverseMovement(adminA,first.publicId,"Correcao",crypto.randomUUID());expect(await count("SELECT COUNT(*) total FROM erp_stock_movements WHERE client_id=?",[adminA.clientId])).toBe(2);});
    it("53 reversal preserves the original movement",async()=>{const s=new ErpService();const item=await stocked(s,"2");const first=(await s.listMovements(adminA,{search:"",productPublicId:item.publicId,page:1,pageSize:20})).items[0];await s.reverseMovement(adminA,first.publicId,"Correcao",crypto.randomUUID());expect(await count("SELECT COUNT(*) total FROM erp_stock_movements WHERE public_id=?",[first.publicId])).toBe(1);});
    it("54 reversal compensates the balance",async()=>{const s=new ErpService();const item=await stocked(s,"2");const first=(await s.listMovements(adminA,{search:"",productPublicId:item.publicId,page:1,pageSize:20})).items[0];await s.reverseMovement(adminA,first.publicId,"Correcao",crypto.randomUUID());expect((await s.getProduct(adminA,item.publicId)).quantity).toBe("0.000");});
    it("55 rejects a second reversal",async()=>{const s=new ErpService();const item=await stocked(s,"2");const first=(await s.listMovements(adminA,{search:"",productPublicId:item.publicId,page:1,pageSize:20})).items[0];await s.reverseMovement(adminA,first.publicId,"Correcao",crypto.randomUUID());await expect(s.reverseMovement(adminA,first.publicId,"Outra",crypto.randomUUID())).rejects.toMatchObject({code:"ALREADY_REVERSED"});});
    it("56 rejects cross-tenant reversal",async()=>{const s=new ErpService();const item=await stocked(s,"2");const first=(await s.listMovements(adminA,{search:"",productPublicId:item.publicId,page:1,pageSize:20})).items[0];await expect(s.reverseMovement(adminB,first.publicId,"Correcao",crypto.randomUUID())).rejects.toMatchObject({code:"NOT_FOUND"});});
    it("57 reversal is idempotent",async()=>{const s=new ErpService();const item=await stocked(s,"2");const first=(await s.listMovements(adminA,{search:"",productPublicId:item.publicId,page:1,pageSize:20})).items[0];const key=crypto.randomUUID();const a=await s.reverseMovement(adminA,first.publicId,"Correcao",key);const b=await s.reverseMovement(adminA,first.publicId,"Correcao",key);expect(b.publicId).toBe(a.publicId);});
    it("58 invalid compensating state fails closed",async()=>{const s=new ErpService();const item=await stocked(s,"2");const input=(await s.listMovements(adminA,{search:"",productPublicId:item.publicId,page:1,pageSize:20})).items[0];await s.moveStock(adminA,{productPublicId:item.publicId,type:"manual_out",quantity:"2",reason:"Saida",idempotencyKey:crypto.randomUUID()});await expect(s.reverseMovement(adminA,input.publicId,"Correcao",crypto.randomUUID())).rejects.toMatchObject({code:"INSUFFICIENT_STOCK"});});
    it("59 records reversal operator and reference",async()=>{const s=new ErpService();const item=await stocked(s,"2");const first=(await s.listMovements(adminA,{search:"",productPublicId:item.publicId,page:1,pageSize:20})).items[0];const reversal=await s.reverseMovement(adminA,first.publicId,"Correcao",crypto.randomUUID());expect([reversal.createdBy,reversal.referenceId]).toEqual([adminA.userId,first.publicId]);});
    it("60 links original and reversal in history",async()=>{const s=new ErpService();const item=await stocked(s,"2");const first=(await s.listMovements(adminA,{search:"",productPublicId:item.publicId,page:1,pageSize:20})).items[0];const reversal=await s.reverseMovement(adminA,first.publicId,"Correcao",crypto.randomUUID());const list=await s.listMovements(adminA,{search:"",productPublicId:item.publicId,page:1,pageSize:20});expect(list.items.find(x=>x.publicId===first.publicId)?.reversalPublicId).toBe(reversal.publicId);});
  });

  describe("summary authorization and isolation",()=>{
    it("61 counts product metrics",async()=>{const s=new ErpService();await product(s);expect((await s.summary(adminA)).metrics.activeProducts).toBe(1);});
    it("62 counts empty stock",async()=>{const s=new ErpService();await product(s);expect((await s.summary(adminA)).metrics.emptyProducts).toBe(1);});
    it("63 counts low stock",async()=>{const s=new ErpService();await stocked(s,"1");expect((await s.summary(adminA)).metrics.lowProducts).toBe(1);});
    it("64 totals quantities",async()=>{const s=new ErpService();await stocked(s,"1.250");expect((await s.summary(adminA)).metrics.totalQuantity).toBe("1.250");});
    it("65 calculates cost value in cents",async()=>{const s=new ErpService();await stocked(s,"2");expect((await s.summary(adminA)).metrics.costValueCents).toBe(2468);});
    it("66 calculates potential sale value in cents",async()=>{const s=new ErpService();await stocked(s,"2");expect((await s.summary(adminA)).metrics.saleValueCents).toBe(4690);});
    it("67 returns recent movements",async()=>{const s=new ErpService();await stocked(s,"1");expect((await s.summary(adminA)).recent).toHaveLength(1);});
    it("68 isolates tenant summaries",async()=>{const s=new ErpService();await product(s,adminA);expect((await s.summary(adminB)).metrics.activeProducts).toBe(0);});
    it("69 empty database returns zeros",async()=>{const metrics=(await new ErpService().summary(adminA)).metrics;expect([metrics.activeProducts,metrics.totalQuantity,metrics.costValueCents]).toEqual([0,"0.000",0]);});
    it("70 viewer and agent can read but cannot write",async()=>{const s=new ErpService();await product(s);expect((await s.listProducts(viewerA,{search:"",stock:"all",sort:"name",direction:"asc",page:1,pageSize:20})).canWrite).toBe(false);expect((await s.summary(agentA)).canWrite).toBe(false);await expect(product(s,agentA)).rejects.toMatchObject({code:"FORBIDDEN"});});
  });
});
